# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='mensaje_operador',
            field=models.BooleanField(default=False),
        ),
    ]
