# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('chat', '0002_usuario_mensaje_operador'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeInicioSesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MensajeUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_contenido', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='mensaje_txt',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='usuario_creador',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='mensaje_operador',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensaje',
            name='object_id',
            field=models.PositiveIntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='id',
            field=models.AutoField(auto_created=True, default=-1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='mensajeusuario',
            name='usuario_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Usuario'),
        ),
        migrations.AddField(
            model_name='mensajeiniciosesion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Usuario'),
        ),
    ]
