# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20160701_0912'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MensajeInicioSesion',
            new_name='MensajeConectadoChat',
        ),
    ]
