# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 22:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_auto_20160702_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajeconectadochat',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='mensajeusuario',
            name='usuario_creador',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='object_id',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='mensaje_contenido',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensaje',
            name='usuario_creador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MensajeConectadoChat',
        ),
        migrations.DeleteModel(
            name='MensajeUsuario',
        ),
    ]
